services:
  - type: web
    name: wc-app-api
    runtime: node
    buildCommand: npm install && npm run etl
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
